name: build API_Identity
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'BACK/**'
      - '.github/workflows/workflow-branche-identity.yaml'

jobs:
  api-identity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build -c Release
        working-directory: ./BACK/API.Identity
