name: build,test for Backend library
on:
  push:
    paths:
      - 'BACK/**'
      - '.github/workflows/workflow-back-library.yaml'

defaults:
  run:
    working-directory: ./BACK/API.Library

jobs:
  api-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Run SpecFlow Tests
        uses: cryptic-wizard/run-specflow-tests@v1.2.0
        with:
          test-assembly-path:BACK/API.Library/Tests/Library.Tests.Specs/bin/Release/net6.0
          test-assembly-dll: Library.Tests.Specs.dll
          test-execution-json: TestExecution.json
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: SpecflowTestResults
          path: BACK/API.Library/LivingDoc.html
      - run: dotnet build API.Library
