name: build,test for Backend library
on:
  push:
    paths:
      - 'BACK/**'
      - '.github/workflows/workflow-back-library.yaml'

defaults:
  run:
    working-directory: ./BACK

jobs:
  api-identity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build API.Library