name: build,test for Backend identity
on:
  push:
    paths:
      - 'BACK/**'
      - '.github/workflows/workflow-back-identity.yaml'

defaults:
  run:
    working-directory: ./BACK
env:
  -BUILD_SOURCE_PATH: API.Identity/bin/Debug/net6.0
jobs:
  api-identity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build API.Identity
      - name: copying build files in distant server using SSH connexion
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.BUILD_SOURCE_PATH }}
          target: API_Identity
      - name: apply commands on distant server using SSH connexion
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd API_Identity
            ls -ltr
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - id: nextversion
        name: next release version
        uses: jenkins-x-plugins/jx-release-version@v2.5.2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.nextversion.outputs.version }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          target_commitish: ${{ github.ref }}